language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env:
        - RELEASE=true
        - GO111MODULE=on
    - go: master
      env:
        - RELEASE=false
        - GO111MODULE=on
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aTURtakcr7jHlFSHAViLY1UI8ZO1ew2pvKS6TYCmnA6G8Im3mdlSeAqifnCRhLV0h7DVZDVLuNiRZdUnTWjHCtpilTVNiYkTkwppdNNai9z8NnHAnmmup2xSBKJEsdS1xsVqrc4aqrXiL2QG6mj90iGbNn7wip9wUb12CsIbcxoprbf0SDIqixt1FFvn0/vh6wxGdqsMckoDW43pbfw9s9jHeRZC1/mn9F/Y3UsLV0Igq/kpnt05wJ00ctKKqVkTn8jifo7QBh6hNwft/pPi54MDcxUrJs/hE2N8TnTjSZL8UgtBtFMIecX4xhP4A2PDdGV8C9wdVPg4V8McpnWNaMGx3LyN4q8r605l0WSKhaBRXJk33QoLA/hCPNxbBCW3ChtzjbjmAx2n04pN3ciSz+aMDW2qTTgMuOeflEITyj03v3CzZPsez8UsJmx9JCi/hFFfgo5HfZABY/1GRrkzItBiOt+3qdW+j1rSiQPzrE2SncABEF7XXY2uNpFUsW+sUU6W7rxBkQsIbNZXqApiwhRPP1Atg10eee8BTTVDJARajt7blSUlRULkPkq8O1Zmnv7/br/ZLsAhU31GCd+PFxpN2MZDlIp/KJ5g8ZDVTjEmedvWv6+PctiOapbZaWe4TRjni5Zcbvr5WvYuzvWca7EKWsubceckVE2dSjuwUhw=
  file: node_exporter_hostname
  on:
    tags: true
    repo: mback2k/node_exporter_hostname
    condition: $RELEASE = true
